{{- if or (ne .Values.hubDeployMode "AddOnTemplate") .Values.featureGates.clusterProfile }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: managed-serviceaccount-addon-manager
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      open-cluster-management.io/addon: managed-serviceaccount
  template:
    metadata:
      labels:
        open-cluster-management.io/addon: managed-serviceaccount
    spec:
      serviceAccount: managed-serviceaccount
      securityContext:
        {{- if semverCompare ">=4.11.0" .Values.hubconfig.ocpVersion }} 
        seccompProfile: 
          type: RuntimeDefault
        {{- end }}
      containers:
        - name: manager
          image: {{ .Values.image }}:{{ .Values.tag | default (print "v" .Chart.Version) }}
          imagePullPolicy: IfNotPresent
          command:
            - /msa
            - manager
          args:
            {{- if gt (int .Values.replicas) 1 }}
            - --leader-elect=true
            {{- end }}
            - --deploy-mode={{ .Values.hubDeployMode }}
            - --agent-image-name={{ .Values.image }}:{{ .Values.tag | default (print "v" .Chart.Version) }}
            {{- if .Values.featureGates }}
            - --feature-gates=EphemeralIdentity={{ .Values.featureGates.ephemeralIdentity | default false}},ClusterProfile={{ .Values.featureGates.clusterProfile | default false}}
            {{- end}}
            {{- if .Values.agentImagePullSecret }}
            - --agent-image-pull-secret={{ .Values.agentImagePullSecret }}
            {{- end}}
{{- end }}
