apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: managed-serviceaccount-addon-manager
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      open-cluster-management.io/addon: managed-serviceaccount
  template:
    metadata:
      labels:
        open-cluster-management.io/addon: managed-serviceaccount
    spec:
      serviceAccount: managed-serviceaccount
      containers:
        - name: manager
          image: {{ .Values.managerImage }}
          command:
            - /manager
          args:
            - --leader-elect=true
            - --agent-image-name={{ .Values.agentImage }}